# Generated by Django 4.0.5 on 2022-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=90)),
                ('release_date', models.CharField(max_length=30)),
                ('lte_exists', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
    ]
